version: '3'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    volumes:
      - /Users/mihailkoruzn/Documents/BotProjects/gptBot4
    command: python bot.py

  redis:
    image: redis:latest
    hostname: "localhost"
    ports:
      - "6379:6379"
