version: '3'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app
    command: python bot.py

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
